[tool.poetry]
name = "meli-challenge-engineer-python"
version = "0.1.0"
description = ""
authors = ["Leonardo Vitorino Silva"]
readme = "README.md"

[tool.poetry.dependencies]
python = "3.12.1"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
